In [16]:
import numpy as np
from glob import glob
import os

ROOT_FRAME_DIR = "/home/lab314/workspace/reid/ds_backend_reid/MCDPT/deepstream_npy_output"

In [17]:
def _extract_embedding(tensor_meta) -> np.ndarray | None:
    try:
        vec = tensor_meta['reid_vector']
        norm = np.linalg.norm(vec)
        return vec / norm if norm > 1e-9 else None
    except Exception as e:
        print(f"[ReID] embed extract error: {e}")
        return None

In [18]:
for i in range(0,3427):
    if os.path.exists(f"{ROOT_FRAME_DIR}/batch_frame_{i}.npy"):
        #iterate through
        
        frame_content = np.load(f"{ROOT_FRAME_DIR}/batch_frame_{200}.npy", allow_pickle=True)
        
        
    break

frame_content[0]['objects']

[{'local_track_id': 3,
  'bbox': array([  0.     , 535.9192 , 255.63252, 333.0308 ], dtype=float32),
  'det_confidence': 0.5052222609519958,
  'reid_vector': array([-7.41699219e-01,  1.12890625e+00, -8.17871094e-01, -1.78125000e+00,
          1.09863281e+00,  5.25878906e-01,  2.89062500e-01, -5.81542969e-01,
          1.17480469e+00,  1.34765625e+00, -2.44140625e+00, -1.19140625e+00,
         -1.96972656e+00,  1.24609375e+00,  1.34570312e+00, -1.75683594e+00,
         -1.12402344e+00, -2.06835938e+00,  2.17773438e-01,  1.92626953e-01,
         -1.19433594e+00, -5.66894531e-01,  4.44580078e-01, -1.43554688e-01,
         -1.29980469e+00, -2.08007812e+00, -8.67187500e-01,  1.89648438e+00,
          2.62695312e+00,  1.51245117e-01,  4.21142578e-01,  9.53613281e-01,
          2.02758789e-01,  1.72851562e+00,  1.52221680e-01, -6.71386719e-02,
         -5.16601562e-01, -7.59277344e-01,  6.91894531e-01, -1.27636719e+00,
          4.75341797e-01, -2.63476562e+00, -9.21630859e-02, -8.26660156e-0

In [19]:
class Tracklet:
    def __init__( 
        self, 
        ds_id: int,
        cam_id: int,
        feature: list[int],
        f_cluster: list[int],
        last_bbox: list[int],
        reid_confidence_score: float,
        cat: int, #1,0,-1
        
    ):
        self.ds_id = ds_id
        self.cam_id = cam_id
        self.f_queue = [[], []]
        self.f_cluster = f_cluster
        self.last_bbox = last_bbox
        self.reid_confidence_score = reid_confidence_score
        self.cat = cat
        self.end_time: int = -1 # logic for end time

    staticmethod
    def _update_end_time(self, end_time: int): self.end_time = end_time
        
    # def 

In [20]:
detections = frame_content[0]['objects']

ds_ids   = [d['local_track_id'] for d in detections]
bboxes   = [d['bbox'] for d in detections]
tracker_confidence = [d['det_confidence'] for d in detections]
features   = [d['reid_vector'] for d in detections]

In [21]:
class STrack(object):
    def __init__(self):
        pass

In [22]:
class botsort(object):
    def __init__(
            self
    ):
        self.tracked_stracks: list[STrack] = []  # type: list[STrack]
        self.lost_stracks: list[STrack] = []  # type: list[STrack]
        self.removed_stracks: list[STrack] = []  # type: list[STrack]

In [23]:
l = [1,2,3,4,5]

In [24]:
l > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [25]:
import numpy as np

In [47]:
output_results = np.array([
    [100.5, 200.0, 150.0, 400.0, 0.95], # A highly confident detection
    [500.0, 300.5, 600.0, 800.0, 0.88], # Another solid detection
    [800.0, 100.0, 850.0, 250.0, 0.45], # A low-confidence detection (might get filtered out)
])

In [52]:
np.array([d['local_track_id'] for d in detections])

array([3, 0, 2, 1])

In [ ]:
ds_local_id = np.array([d['local_track_id'] for d in detections])

In [54]:
scores = output_results[:, 4]
bboxes = output_results[:, :4]
classes = output_results[:, -1]

In [56]:
ds_local_id

array([3, 0, 2, 1])

In [28]:
scores

array([0.95, 0.88, 0.45])

In [29]:
lowest_inds = scores > 0.8
bboxes = bboxes[lowest_inds]
scores = scores[lowest_inds]
classes = classes[lowest_inds]

In [11]:
bboxes

array([[100.5, 200. , 150. , 400. ],
       [500. , 300.5, 600. , 800. ]])