In [57]:
import numpy as np
from glob import glob
import os

ROOT_FRAME_DIR = "/home/lab314/workspace/reid/ds_backend_reid/MCDPT/deepstream_npy_output"

In [58]:
def _extract_embedding(tensor_meta) -> np.ndarray | None:
    try:
        vec = tensor_meta['reid_vector']
        norm = np.linalg.norm(vec)
        return vec / norm if norm > 1e-9 else None
    except Exception as e:
        print(f"[ReID] embed extract error: {e}")
        return None

In [59]:
for i in range(0,3427):
    if os.path.exists(f"{ROOT_FRAME_DIR}/batch_frame_{i}.npy"):
        #iterate through
        
        frame_content = np.load(f"{ROOT_FRAME_DIR}/batch_frame_{200}.npy", allow_pickle=True)
        
        
    break

frame_content[0]['objects']

[{'local_track_id': 3,
  'bbox': array([  0.     , 535.9192 , 255.63252, 333.0308 ], dtype=float32),
  'det_confidence': 0.5052222609519958,
  'reid_vector': array([1.05125000e+02, 1.13375000e+02, 2.61230469e-01, 1.11062500e+02,
         1.11000000e+02, 1.99218750e-01, 9.68125000e+01, 1.18250000e+02,
         1.56860352e-01, 9.27500000e+01, 9.12500000e+01, 5.54199219e-01,
         1.02125000e+02, 1.39750000e+02, 1.40991211e-01, 9.38750000e+01,
         1.53375000e+02, 3.02490234e-01, 8.26875000e+01, 6.83750000e+01,
         6.41113281e-01, 1.46750000e+02, 1.89250000e+02, 3.23974609e-01,
         1.20187500e+02, 1.98375000e+02, 3.18603516e-01, 1.61375000e+02,
         1.99750000e+02, 3.04443359e-01, 1.29875000e+02, 1.97875000e+02,
         1.86157227e-01, 1.64250000e+02, 1.95625000e+02, 3.35693359e-01,
         1.24937500e+02, 1.99625000e+02, 1.83593750e-01, 1.44375000e+02,
         1.91625000e+02, 2.46704102e-01, 1.25312500e+02, 2.03250000e+02,
         3.11279297e-01, 7.83750000e+01, 

In [60]:
class Tracklet:
    def __init__( 
        self, 
        ds_id: int,
        cam_id: int,
        feature: list[int],
        f_cluster: list[int],
        last_bbox: list[int],
        reid_confidence_score: float,
        cat: int, #1,0,-1
        
    ):
        self.ds_id = ds_id
        self.cam_id = cam_id
        self.f_queue = [[], []]
        self.f_cluster = f_cluster
        self.last_bbox = last_bbox
        self.reid_confidence_score = reid_confidence_score
        self.cat = cat
        self.end_time: int = -1 # logic for end time

    staticmethod
    def _update_end_time(self, end_time: int): self.end_time = end_time
        
    # def 

In [61]:
detections = frame_content[0]['objects']

ds_ids   = [d['local_track_id'] for d in detections]
bboxes   = [d['bbox'] for d in detections]
tracker_confidence = [d['det_confidence'] for d in detections]
features   = [d['reid_vector'] for d in detections]

In [65]:
frame_content

array([{'frame_id': 200, 'sensor_id': 'platform_0_camera_A', 'objects': [{'local_track_id': 3, 'bbox': array([  0.     , 535.9192 , 255.63252, 333.0308 ], dtype=float32), 'det_confidence': 0.5052222609519958, 'reid_vector': array([1.05125000e+02, 1.13375000e+02, 2.61230469e-01, 1.11062500e+02,
              1.11000000e+02, 1.99218750e-01, 9.68125000e+01, 1.18250000e+02,
              1.56860352e-01, 9.27500000e+01, 9.12500000e+01, 5.54199219e-01,
              1.02125000e+02, 1.39750000e+02, 1.40991211e-01, 9.38750000e+01,
              1.53375000e+02, 3.02490234e-01, 8.26875000e+01, 6.83750000e+01,
              6.41113281e-01, 1.46750000e+02, 1.89250000e+02, 3.23974609e-01,
              1.20187500e+02, 1.98375000e+02, 3.18603516e-01, 1.61375000e+02,
              1.99750000e+02, 3.04443359e-01, 1.29875000e+02, 1.97875000e+02,
              1.86157227e-01, 1.64250000e+02, 1.95625000e+02, 3.35693359e-01,
              1.24937500e+02, 1.99625000e+02, 1.83593750e-01, 1.44375000e+02,
   

In [64]:
detections = frame_content[:['objects']
have_reid = any(d["reid_vector"] is not None for d in detections)
have_reid

SyntaxError: '[' was never closed (1386972411.py, line 1)

In [21]:
class STrack(object):
    def __init__(self):
        pass

In [22]:
class botsort(object):
    def __init__(
            self
    ):
        self.tracked_stracks: list[STrack] = []  # type: list[STrack]
        self.lost_stracks: list[STrack] = []  # type: list[STrack]
        self.removed_stracks: list[STrack] = []  # type: list[STrack]

In [23]:
l = [1,2,3,4,5]

In [24]:
l > 3

TypeError: '>' not supported between instances of 'list' and 'int'

In [25]:
import numpy as np

In [47]:
output_results = np.array([
    [100.5, 200.0, 150.0, 400.0, 0.95], # A highly confident detection
    [500.0, 300.5, 600.0, 800.0, 0.88], # Another solid detection
    [800.0, 100.0, 850.0, 250.0, 0.45], # A low-confidence detection (might get filtered out)
])

In [52]:
np.array([d['local_track_id'] for d in detections])

array([3, 0, 2, 1])

In [ ]:
ds_local_id = np.array([d['local_track_id'] for d in detections])

In [54]:
scores = output_results[:, 4]
bboxes = output_results[:, :4]
classes = output_results[:, -1]

In [56]:
ds_local_id

array([3, 0, 2, 1])

In [28]:
scores

array([0.95, 0.88, 0.45])

In [29]:
lowest_inds = scores > 0.8
bboxes = bboxes[lowest_inds]
scores = scores[lowest_inds]
classes = classes[lowest_inds]

In [11]:
bboxes

array([[100.5, 200. , 150. , 400. ],
       [500. , 300.5, 600. , 800. ]])